name: Vercel Production Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read
  actions: read
  checks: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

  Database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: awaismalik01/github-actions/secure-flyway-migration@v1
        with:
          infisical-method: "oidc"
          infisical-identity-id: ${{ secrets.INFISICAL_MACHINE_ID }}
          infisical-project-slug: ${{ secrets.INFISICAL_NEON_DB_FLYWAY_SLUG }}
          infisical-secret-path: ${{ secrets.INFISICAL_NEON_SECRET_PATH }}
          infisical-env-slug: "prod"
          migration-path: "./db-migrations"

  Deploy-Production:
    needs: [Build, Database]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - uses: awaismalik01/github-actions/nest-vercel-deploy@v1
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          target: production
          infisical_method: "oidc"
          infisical_identity_id: ${{ secrets.INFISICAL_MACHINE_ID }}
          infisical_project_slug: ${{ secrets.INFISICAL_PROJECT_SLUG }}
          infisical_env_slug: "prod"
